# Generated by Django 4.2.9 on 2024-04-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customer_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
