# Generated by Django 4.2.9 on 2024-04-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='description',
        ),
    ]
